# Generated by Django 2.0 on 2017-12-24 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171224_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_subscription_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserSubscriptions'),
        ),
    ]
