# Generated by Django 2.0 on 2017-12-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171224_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='user_subscription_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_subscription_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='Subscriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Subscription'),
        ),
        migrations.AlterField(
            model_name='usersubscriptions',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
