# Generated by Django 2.0 on 2017-12-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171225_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_subscription_id',
        ),
    ]
