# Generated by Django 2.0 on 2017-12-26 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscriptions',
            name='Subscriptions',
        ),
        migrations.RemoveField(
            model_name='usersubscriptions',
            name='users',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_subscription_id',
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Subscription'),
        ),
        migrations.DeleteModel(
            name='UserSubscriptions',
        ),
    ]
