# Generated by Django 2.0 on 2017-12-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_subscription_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_path',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
