# Generated by Django 2.0 on 2018-01-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180101_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_limit',
            field=models.IntegerField(default=5),
        ),
    ]
