# Generated by Django 2.0 on 2018-01-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20180114_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='socket_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
