# Generated by Django 2.0 on 2018-02-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_socket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rooms_joined',
            field=models.IntegerField(null=True),
        ),
    ]
