# Generated by Django 2.0 on 2018-02-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180211_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rooms_joined',
            field=models.IntegerField(default=1),
        ),
    ]
