# Generated by Django 2.0 on 2018-02-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180211_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rooms_joined',
        ),
    ]
