# Generated by Django 2.0 on 2018-02-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_user_rooms_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rooms_joined',
            field=models.IntegerField(default=1),
        ),
    ]
