# Generated by Django 2.0 on 2017-12-23 15:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_auto_20171223_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='tag',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2017, 12, 23, 15, 34, 51, 727915, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(default=-2017, on_delete=django.db.models.deletion.DO_NOTHING, to='chatroom.Chatroom'),
            preserve_default=False,
        ),
    ]
