# Generated by Django 2.0 on 2017-12-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0005_auto_20171223_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
