# Generated by Django 2.0 on 2017-12-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0006_auto_20171223_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrooms',
            old_name='rooms',
            new_name='room',
        ),
    ]
