# Generated by Django 2.0 on 2017-12-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0008_auto_20171225_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
