# Generated by Django 2.0 on 2018-01-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0010_chatroom_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
