# Generated by Django 2.0 on 2018-01-29 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0012_auto_20180129_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateroom',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='privateroom',
            name='invitee_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='private_room',
        ),
        migrations.RemoveField(
            model_name='userrooms',
            name='user',
        ),
        migrations.AddField(
            model_name='userrooms',
            name='host_id',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrooms',
            name='invitee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PrivateRoom',
        ),
    ]
