# Generated by Django 2.0 on 2018-02-01 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatroom', '0013_auto_20180129_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('invitee_name', models.CharField(max_length=50)),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='host_id', to=settings.AUTH_USER_MODEL)),
                ('invitee_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitee_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
