# Generated by Django 2.0 on 2018-02-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0014_conversations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversations',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='conversations',
            old_name='invitee_id',
            new_name='invitee',
        ),
    ]
