# Generated by Django 2.0 on 2018-02-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0014_conversations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversations',
            name='host_id',
        ),
        migrations.RemoveField(
            model_name='conversations',
            name='invitee_id',
        ),
        migrations.RenameField(
            model_name='userrooms',
            old_name='host_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='userrooms',
            name='invitee_id',
        ),
        migrations.DeleteModel(
            name='Conversations',
        ),
    ]
