# Generated by Django 2.0 on 2018-02-04 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0015_auto_20180204_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrooms',
            old_name='host_id',
            new_name='host',
        ),
        migrations.RenameField(
            model_name='userrooms',
            old_name='invitee_id',
            new_name='invitee',
        ),
    ]
